name: Python application

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: python-3.11
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unittest
        run: |
          python -m pytest tests/
      - name: MyPy
        run: |
          mypy app/
      - name: Black
        run: |
          black --check --diff app/
      - name: Flake8
        run: |
          flake8 app/
      - name: Isort
        run: |
          isort --check-only --diff app/