name: Python application
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unittest
      run: |
        python -m pytest tests/
    - name: MyPy
      run: |
        mypy app/
    - name: Black
      run: |
        black --check --diff app/
    - name: Flake8
      run: |
        flake8 app/
    - name: Isort
      run: |
        isort --check-only --diff app/
